-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 13:17:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tever
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tever
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tever` DEFAULT CHARACTER SET utf8 ;
USE `tever` ;

-- -----------------------------------------------------
-- Table `tever`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tever`.`funcionarios` (
  `cod_fun` INT NOT NULL AUTO_INCREMENT,
  `nome_fun` VARCHAR(45) NOT NULL,
  `cpf_fun` VARCHAR(11) NOT NULL,
  `usuario_fun` VARCHAR(45) NOT NULL,
  `senha_fun` VARCHAR(45) NOT NULL,
  `telefone_fun` VARCHAR(11) NOT NULL,
  `salario_fun` DECIMAL(9,2) NOT NULL,
  `endereco_fun` VARCHAR(45) NOT NULL,
  `data_nasc_fun` VARCHAR(45) NOT NULL,
  `email_fun` VARCHAR(45) NOT NULL,
  `status_fun` VARCHAR(45) NOT NULL,
  `funcao_fun` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tever`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tever`.`vendas` (
  `cod_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` VARCHAR(45) NOT NULL,
  `funcionarios_cod_fun` INT NOT NULL,
  PRIMARY KEY (`cod_venda`),
  INDEX `fk_vendas_funcionarios_idx` (`funcionarios_cod_fun` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_funcionarios`
    FOREIGN KEY (`funcionarios_cod_fun`)
    REFERENCES `tever`.`funcionarios` (`cod_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tever`.`televisores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tever`.`televisores` (
  `cod_tel` INT NOT NULL AUTO_INCREMENT,
  `marca_tel` VARCHAR(45) NOT NULL,
  `modelo_tel` VARCHAR(45) NOT NULL,
  `preco_tel` DECIMAL(9,2) NOT NULL,
  `resolucao_tel` VARCHAR(10) NOT NULL,
  `conectividade_tel` VARCHAR(45) NOT NULL,
  `streaming_tel` CHAR(1) NOT NULL,
  `fila_compra_tel` CHAR(1) NOT NULL,
  `vendas_cod_venda` INT NOT NULL,
  PRIMARY KEY (`cod_tel`),
  INDEX `fk_televisores_vendas1_idx` (`vendas_cod_venda` ASC) VISIBLE,
  CONSTRAINT `fk_televisores_vendas1`
    FOREIGN KEY (`vendas_cod_venda`)
    REFERENCES `tever`.`vendas` (`cod_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `funcionarios` (`nome_fun`,`cpf_fun`,`usuario_fun`,`senha_fun`,`telefone_fun`,`salario_fun`,`endereco_fun`,`data_nasc_fun`,`email_fun`,`status_fun`,`funcao_fun`) VALUES ('matheus','11122233344','admin','1','11988880000',7.50,'Rua do Cachorro','03/08/2000','matheus@example.com','ativo','administrador');
INSERT INTO `funcionarios` (`nome_fun`,`cpf_fun`,`usuario_fun`,`senha_fun`,`telefone_fun`,`salario_fun`,`endereco_fun`,`data_nasc_fun`,`email_fun`,`status_fun`,`funcao_fun`) VALUES ('bruno','11122233355','brune','1','11998880000',5.50,'Rua do Cavalo','09/12/1451','bruno@example.com','ativo','estoquista');
INSERT INTO `funcionarios` (`nome_fun`,`cpf_fun`,`usuario_fun`,`senha_fun`,`telefone_fun`,`salario_fun`,`endereco_fun`,`data_nasc_fun`,`email_fun`,`status_fun`,`funcao_fun`) VALUES ('ana','11122233366','ana','1','11988888000',8.21,'Rua da Onça','13/10/1999','ana@example.com','ativo','vendedor');

INSERT INTO `vendas` (`data_venda`,`funcionarios_cod_fun`) VALUES ('00-00-0000',1);

INSERT INTO `televisores` (`marca_tel`,`modelo_tel`,`preco_tel`,`resolucao_tel`,`conectividade_tel`,`streaming_tel`,`fila_compra_tel`,`vendas_cod_venda`) VALUES ('Semp','Smart TV 50\" Roku',1975.50,'4K UHD','Wi-Fi','S','N',1);
INSERT INTO `televisores` (`marca_tel`,`modelo_tel`,`preco_tel`,`resolucao_tel`,`conectividade_tel`,`streaming_tel`,`fila_compra_tel`,`vendas_cod_venda`) VALUES ('TCL','Smart TV 32\"',1044.00,'Full HD','Wi-Fi - Bluetooth','S','N',1);
INSERT INTO `televisores` (`marca_tel`,`modelo_tel`,`preco_tel`,`resolucao_tel`,`conectividade_tel`,`streaming_tel`,`fila_compra_tel`,`vendas_cod_venda`) VALUES ('Philco','TV Digital 24\"',930.00,'HD','Não','N','N',1);
INSERT INTO `televisores` (`marca_tel`,`modelo_tel`,`preco_tel`,`resolucao_tel`,`conectividade_tel`,`streaming_tel`,`fila_compra_tel`,`vendas_cod_venda`) VALUES ('LG','Smart TV 32\"',1253.66,'HD LED','Wi-Fi - Bluetooth','S','N',1);
INSERT INTO `televisores` (`marca_tel`,`modelo_tel`,`preco_tel`,`resolucao_tel`,`conectividade_tel`,`streaming_tel`,`fila_compra_tel`,`vendas_cod_venda`) VALUES ('Samsung','Smart TV 50\"',2280.00,'4K UHD','Wi-Fi','S','N',1);

